import = [
    "~/.config/alacritty/themes/afterglow.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 25
y = 20

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left", mods = "Alt", chars = "\u001BB" },
    { key = "Back", mods = "Alt", chars = "\u001b\u007f" }, # Delete word
    { key = "Back", mods = "Command", chars = "\u0015" }, # Delete line
    { key = "T", mods = "Command", chars = "\u0002c" }, # open new tmux window
    { key = "D", mods = "Command|Shift", chars = "\u0002\"" }, # split tmux window vertically
    { key = "D", mods = "Command", chars = "\u0002%" }, # split tmux window horizontally
    { key = "W", mods = "Command", chars = "\u0002x" }, # kill the current pane
    { key = "RBracket", mods = "Command", chars = "\u0002p" }, # switch to next tmux window
]

