import = [
    # "~/.config/alacritty/themes/afterglow.toml"
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1
option_as_alt = "Both"

[window.padding]
# x = 25
# y = 20
x = 5
y = 5

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
    { key = "Back", mods = "Alt", chars = "\u001b\u007f" }, # Delete word
    { key = "Back", mods = "Command", chars = "\u0015" }, # Delete line
    # { key = "Right", mods = "Alt", chars = "\u001BF" },
    # { key = "Left", mods = "Alt", chars = "\u001BB" },
]

